# Generated by Django 4.0.3 on 2022-03-24 11:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('url_builder', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='TinyURL',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('url', models.URLField(unique=True)),
                ('shortcutCode', models.CharField(max_length=6, unique=True)),
                ('date', models.DateField(auto_now_add=True, verbose_name='Date of creation of the shorcut')),
                ('username', models.CharField(max_length=20)),
                ('numberAccess', models.IntegerField(default=0)),
            ],
        ),
        migrations.DeleteModel(
            name='Builder',
        ),
    ]
