# Generated by Django 4.0.3 on 2022-03-24 13:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('url_builder', '0002_tinyurl_delete_builder'),
    ]

    operations = [
        migrations.AlterField(
            model_name='tinyurl',
            name='shortcutCode',
            field=models.CharField(max_length=6),
        ),
    ]
