# Generated by Django 4.0.3 on 2022-03-24 13:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('url_builder', '0004_alter_tinyurl_shortcutcode'),
    ]

    operations = [
        migrations.AlterField(
            model_name='tinyurl',
            name='shortcutCode',
            field=models.CharField(default='abcde', max_length=6),
        ),
    ]
