# Generated by Django 4.0.3 on 2022-03-24 15:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('url_builder', '0005_alter_tinyurl_shortcutcode'),
    ]

    operations = [
        migrations.AlterField(
            model_name='tinyurl',
            name='shortcutCode',
            field=models.CharField(max_length=6, unique=True),
        ),
        migrations.AlterField(
            model_name='tinyurl',
            name='url',
            field=models.URLField(),
        ),
    ]
