# Generated by Django 4.0.3 on 2022-03-24 15:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('url_builder', '0006_alter_tinyurl_shortcutcode_alter_tinyurl_url'),
    ]

    operations = [
        migrations.AlterField(
            model_name='tinyurl',
            name='numberAccess',
            field=models.IntegerField(default=1),
        ),
    ]
